run:
  deadline: 5m

linters-settings:
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 4

linters:
  enable-all: true
  disable:
    - depguard
    - dupl
    - errcheck
    - gosimple
    - staticcheck
    - lll
    - prealloc
    - gochecknoglobals
    - gochecknoinits
    - funlen
    - tagliatelle
    - varnamelen
    - wsl
    - nlreturn
    - mnd
    - testpackage
    - exhaustruct
    - tenv
