version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - errcheck
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - lll
    - mnd
    - nlreturn
    - prealloc
    - staticcheck
    - tagliatelle
    - testpackage
    - varnamelen
    - wsl
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 4
    gocyclo:
      min-complexity: 20
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: _test\.go
        linters:
          - gosec
          - goconst
          - paralleltest
          - tparallel
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
