name: test
on: 
  pull_request:
  push:
    branches:    
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version: stable
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.12
    - name: Test
      run: go test -v -race ./...
